
CURRENCY_INFO = {
    "AED": {"label": "United Arab Emirates - Dirham", "symbol": "د.إ"},
    "AFN": {"label": "Afghanistan - Afghani", "symbol": "؋"},
    "ALL": {"label": "Albania - Lek", "symbol": "L"},
    "AMD": {"label": "Armenia - Dram", "symbol": "֏"},
    "ANG": {"label": "Netherlands Antilles - Guilder", "symbol": "ƒ"},
    "AOA": {"label": "Angola - Kwanza", "symbol": "Kz"},
    "ARS": {"label": "Argentina - Peso", "symbol": "$"},
    "AUD": {"label": "Australia - Dollar", "symbol": "A$"},
    "AWG": {"label": "Aruba - Florin", "symbol": "ƒ"},
    "AZN": {"label": "Azerbaijan - Manat", "symbol": "₼"},
    "BAM": {"label": "Bosnia-Herzegovina - Mark", "symbol": "KM"},
    "BBD": {"label": "Barbados - Dollar", "symbol": "$"},
    "BDT": {"label": "Bangladesh - Taka", "symbol": "৳"},
    "BGN": {"label": "Bulgaria - Lev", "symbol": "лв"},
    "BHD": {"label": "Bahrain - Dinar", "symbol": ".د.ب"},
    "BIF": {"label": "Burundi - Franc", "symbol": "FBu"},
    "BMD": {"label": "Bermuda - Dollar", "symbol": "$"},
    "BND": {"label": "Brunei - Dollar", "symbol": "B$"},
    "BOB": {"label": "Bolivia - Boliviano", "symbol": "Bs."},
    "BRL": {"label": "Brazil - Real", "symbol": "R$"},
    "BSD": {"label": "Bahamas - Dollar", "symbol": "$"},
    "BTN": {"label": "Bhutan - Ngultrum", "symbol": "Nu."},
    "BWP": {"label": "Botswana - Pula", "symbol": "P"},
    "BYN": {"label": "Belarus - Ruble", "symbol": "Br"},
    "BZD": {"label": "Belize - Dollar", "symbol": "$"},
    "CAD": {"label": "Canada - Dollar", "symbol": "C$"},
    "CDF": {"label": "Congo - Franc", "symbol": "FC"},
    "CHF": {"label": "Switzerland - Franc", "symbol": "Fr"},
    "CLP": {"label": "Chile - Peso", "symbol": "$"},
    "CNY": {"label": "China - Yuan", "symbol": "¥"},
    "COP": {"label": "Colombia - Peso", "symbol": "$"},
    "CRC": {"label": "Costa Rica - Colon", "symbol": "₡"},
    "CUP": {"label": "Cuba - Peso", "symbol": "$"},
    "CVE": {"label": "Cape Verde - Escudo", "symbol": "$"},
    "CZK": {"label": "Czech Republic - Koruna", "symbol": "Kč"},
    "DJF": {"label": "Djibouti - Franc", "symbol": "Fdj"},
    "DKK": {"label": "Denmark - Krone", "symbol": "kr"},
    "DOP": {"label": "Dominican Republic - Peso", "symbol": "RD$"},
    "DZD": {"label": "Algeria - Dinar", "symbol": "د.ج"},
    "EGP": {"label": "Egypt - Pound", "symbol": "£"},
    "ERN": {"label": "Eritrea - Nakfa", "symbol": "Nfk"},
    "ETB": {"label": "Ethiopia - Birr", "symbol": "Br"},
    "EUR": {"label": "European Union - Euro", "symbol": "€"},
    "FJD": {"label": "Fiji - Dollar", "symbol": "$"},
    "FKP": {"label": "Falkland Islands - Pound", "symbol": "£"},
    "FOK": {"label": "Faroe Islands - Króna", "symbol": "kr"},
    "GBP": {"label": "United Kingdom - Pound", "symbol": "£"},
    "GEL": {"label": "Georgia - Lari", "symbol": "₾"},
    "GGP": {"label": "Guernsey - Pound", "symbol": "£"},
    "GHS": {"label": "Ghana - Cedi", "symbol": "GH₵"},
    "GIP": {"label": "Gibraltar - Pound", "symbol": "£"},
    "GMD": {"label": "Gambia - Dalasi", "symbol": "D"},
    "GNF": {"label": "Guinea - Franc", "symbol": "FG"},
    "GTQ": {"label": "Guatemala - Quetzal", "symbol": "Q"},
    "GYD": {"label": "Guyana - Dollar", "symbol": "$"},
    "HKD": {"label": "Hong Kong - Dollar", "symbol": "HK$"},
    "HNL": {"label": "Honduras - Lempira", "symbol": "L"},
    "HTG": {"label": "Haiti - Gourde", "symbol": "G"},
    "HUF": {"label": "Hungary - Forint", "symbol": "Ft"},
    "IDR": {"label": "Indonesia - Rupiah", "symbol": "Rp"},
    "ILS": {"label": "Israel - Shekel", "symbol": "₪"},
    "IMP": {"label": "Isle of Man - Pound", "symbol": "£"},
    "INR": {"label": "India - Rupee", "symbol": "₹"},
    "IQD": {"label": "Iraq - Dinar", "symbol": "ع.د"},
    "IRR": {"label": "Iran - Rial", "symbol": "﷼"},
    "ISK": {"label": "Iceland - Króna", "symbol": "kr"},
    "JEP": {"label": "Jersey - Pound", "symbol": "£"},
    "JMD": {"label": "Jamaica - Dollar", "symbol": "$"},
    "JOD": {"label": "Jordan - Dinar", "symbol": "د.ا"},
    "JPY": {"label": "Japan - Yen", "symbol": "¥"},
    "KES": {"label": "Kenya - Shilling", "symbol": "KSh"},
    "KGS": {"label": "Kyrgyzstan - Som", "symbol": "сом"},
    "KHR": {"label": "Cambodia - Riel", "symbol": "៛"},
    "KID": {"label": "Kiribati - Dollar", "symbol": "$"},
    "KMF": {"label": "Comoros - Franc", "symbol": "CF"},
    "KRW": {"label": "South Korea - Won", "symbol": "₩"},
    "KWD": {"label": "Kuwait - Dinar", "symbol": "د.ك"},
    "KYD": {"label": "Cayman Islands - Dollar", "symbol": "$"},
    "KZT": {"label": "Kazakhstan - Tenge", "symbol": "₸"},
    "LAK": {"label": "Laos - Kip", "symbol": "₭"},
    "LBP": {"label": "Lebanon - Pound", "symbol": "ل.ل"},
    "LKR": {"label": "Sri Lanka - Rupee", "symbol": "Rs"},
    "LRD": {"label": "Liberia - Dollar", "symbol": "$"},
    "LSL": {"label": "Lesotho - Loti", "symbol": "L"},
    "LYD": {"label": "Libya - Dinar", "symbol": "ل.د"},
    "MAD": {"label": "Morocco - Dirham", "symbol": "د.m."},
    "MDL": {"label": "Moldova - Leu", "symbol": "L"},
    "MGA": {"label": "Madagascar - Ariary", "symbol": "Ar"},
    "MKD": {"label": "North Macedonia - Denar", "symbol": "ден"},
    "MMK": {"label": "Myanmar - Kyat", "symbol": "K"},
    "MNT": {"label": "Mongolia - Tögrög", "symbol": "₮"},
    "MOP": {"label": "Macau - Pataca", "symbol": "P"},
    "MRU": {"label": "Mauritania - Ouguiya", "symbol": "UM"},
    "MUR": {"label": "Mauritius - Rupee", "symbol": "₨"},
    "MVR": {"label": "Maldives - Rufiyaa", "symbol": ".ރ"},
    "MWK": {"label": "Malawi - Kwacha", "symbol": "MK"},
    "MXN": {"label": "Mexico - Peso", "symbol": "$"},
    "MYR": {"label": "Malaysia - Ringgit", "symbol": "RM"},
    "MZN": {"label": "Mozambique - Metical", "symbol": "MT"},
    "NAD": {"label": "Namibia - Dollar", "symbol": "$"},
    "NGN": {"label": "Nigeria - Naira", "symbol": "₦"},
    "NIO": {"label": "Nicaragua - Córdoba", "symbol": "C$"},
    "NOK": {"label": "Norway - Krone", "symbol": "kr"},
    "NPR": {"label": "Nepal - Rupee", "symbol": "₨"},
    "NZD": {"label": "New Zealand - Dollar", "symbol": "$"},
    "OMR": {"label": "Oman - Rial", "symbol": "ر.ع."},
    "PAB": {"label": "Panama - Balboa", "symbol": "B/."},
    "PEN": {"label": "Peru - Sol", "symbol": "S/."},
    "PGK": {"label": "Papua New Guinea - Kina", "symbol": "K"},
    "PHP": {"label": "Philippines - Peso", "symbol": "₱"},
    "PKR": {"label": "Pakistan - Rupee", "symbol": "₨"},
    "PLN": {"label": "Poland - Złoty", "symbol": "zł"},
    "PYG": {"label": "Paraguay - Guaraní", "symbol": "₲"},
    "QAR": {"label": "Qatar - Riyal", "symbol": "ر.ق"},
    "RON": {"label": "Romania - Leu", "symbol": "lei"},
    "RSD": {"label": "Serbia - Dinar", "symbol": "дин."},
    "RUB": {"label": "Russia - Ruble", "symbol": "₽"},
    "RWF": {"label": "Rwanda - Franc", "symbol": "FRw"},
    "SAR": {"label": "Saudi Arabia - Riyal", "symbol": "ر.س"},
    "SBD": {"label": "Solomon Islands - Dollar", "symbol": "$"},
    "SCR": {"label": "Seychelles - Rupee", "symbol": "₨"},
    "SDG": {"label": "Sudan - Pound", "symbol": "ج.س."},
    "SEK": {"label": "Sweden - Krona", "symbol": "kr"},
    "SGD": {"label": "Singapore - Dollar", "symbol": "S$"},
    "SHP": {"label": "Saint Helena - Pound", "symbol": "£"},
    "SLL": {"label": "Sierra Leone - Leone", "symbol": "Le"},
    "SOS": {"label": "Somalia - Shilling", "symbol": "Sh"},
    "SRD": {"label": "Suriname - Dollar", "symbol": "$"},
    "SSP": {"label": "South Sudan - Pound", "symbol": "£"},
    "STN": {"label": "São Tomé and Príncipe - Dobra", "symbol": "Db"},
    "SYP": {"label": "Syria - Pound", "symbol": "£"},
    "SZL": {"label": "Eswatini - Lilangeni", "symbol": "L"},
    "THB": {"label": "Thailand - Baht", "symbol": "฿"},
    "TJS": {"label": "Tajikistan - Somoni", "symbol": "SM"},
    "TMT": {"label": "Turkmenistan - Manat", "symbol": "T"},
    "TND": {"label": "Tunisia - Dinar", "symbol": "د.ت"},
    "TOP": {"label": "Tonga - Paʻanga", "symbol": "T$"},
    "TRY": {"label": "Turkey - Lira", "symbol": "₺"},
    "TTD": {"label": "Trinidad and Tobago - Dollar", "symbol": "$"},
    "TVD": {"label": "Tuvalu - Dollar", "symbol": "$"},
    "TWD": {"label": "Taiwan - New Dollar", "symbol": "NT$"},
    "TZS": {"label": "Tanzania - Shilling", "symbol": "TSh"},
    "UAH": {"label": "Ukraine - Hryvnia", "symbol": "₴"},
    "UGX": {"label": "Uganda - Shilling", "symbol": "USh"},
    "USD": {"label": "United States - Dollar", "symbol": "$"},
    "UYU": {"label": "Uruguay - Peso", "symbol": "$U"},
    "UZS": {"label": "Uzbekistan - Som", "symbol": "so'm"},
    "VES": {"label": "Venezuela - Bolívar", "symbol": "Bs.S"},
    "VND": {"label": "Vietnam - Đồng", "symbol": "₫"},
    "VUV": {"label": "Vanuatu - Vatu", "symbol": "VT"},
    "WST": {"label": "Samoa - Tala", "symbol": "T"},
    "XAF": {"label": "CEMAC - Franc", "symbol": "FCFA"},
    "XCD": {"label": "East Caribbean - Dollar", "symbol": "$"},
    "XDR": {"label": "IMF - Special Drawing Rights", "symbol": "SDR"},
    "XOF": {"label": "UEMOA - Franc", "symbol": "CFA"},
    "XPF": {"label": "CFP - Franc", "symbol": "₣"},
    "YER": {"label": "Yemen - Rial", "symbol": "﷼"},
    "ZAR": {"label": "South Africa - Rand", "symbol": "R"},
    "ZMW": {"label": "Zambia - Kwacha", "symbol": "ZK"},
    "ZWL": {"label": "Zimbabwe - Dollar", "symbol": "$"}
}